# Generated by Django 5.0.3 on 2024-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_birthday_profile_birth_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
