# Generated by Django 5.0.3 on 2024-04-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_birthday_profile_b_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dream',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dream_destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_anime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_anime_character',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_book',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_movie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_song',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
