# Generated by Django 5.0.3 on 2024-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry_publisher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
