# Generated by Django 5.0.6 on 2024-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_anonymous_alter_topic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
