# Generated by Django 5.0.6 on 2024-05-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_remove_entry_tags_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
