# Generated by Django 5.0.6 on 2024-05-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_entry_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
