# Generated by Django 5.0.6 on 2024-05-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_entry_towntalk'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='town_talks',
            field=models.JSONField(default=list),
        ),
    ]
